name: selene
description: "An AI-powered Flutter application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  google_generative_ai: ^0.2.2
  intl: ^0.17.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  cloud_firestore: ^4.17.5
  fluttertoast: ^8.2.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Add this section to include your .env file as an asset
  assets:
    - .env
    - assets/images/
